// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vardwmrctfckcrbsmynl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhcmR3bXJjdGZja2NyYnNteW5sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzU2MjUwNjcsImV4cCI6MjA5MTIwMTA2N30.zC-OrCSehxl9nVRKsCOkEyBnfzEhwGMooaW8U9otmdU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});